import test from 'node:test'; import assert from 'node:assert/strict'; import { readFile, access } from 'node:fs/promises'; import { filterProducts, sanitizeCart, cartTotal, orderMessage } from '../catalog-utils.js';
const {products}=JSON.parse(await readFile(new URL('../catalog.json',import.meta.url)));
test('Busca ignora acentos e filtra categorias e favoritos',()=>{assert.equal(filterProducts(products,{query:'omega'})[0].id,3);assert.ok(filterProducts(products,{category:'Área Infantil'}).every(p=>p.category==='Área Infantil'));assert.equal(filterProducts(products,{favorites:[31,32]}).length,2);assert.equal(filterProducts(products,{query:'inexistente123'}).length,0);});
test('Carrinho rejeita dados inválidos, exige tamanho e limita quantidades',()=>{assert.deepEqual(sanitizeCart([{id:999,qty:1},{id:31,qty:-1},{id:31,qty:1.5},{id:7,qty:1},{id:7,variant:'FAKE',qty:2}],products),[]);assert.deepEqual(sanitizeCart([{id:31,qty:2},{id:31,qty:100}],products),[{id:31,variant:'',qty:99}]);assert.equal(sanitizeCart([{id:7,variant:'P',qty:2}],products).length,1);});
test('Total usa centavos e mensagem mantém quantidade e tamanho',()=>{const cart=[{id:31,qty:2,variant:''},{id:7,qty:1,variant:'P'}];assert.equal(cartTotal(cart,products),5797);assert.match(orderMessage(cart,products),/tamanho P, pacote com 34 fraldas/);assert.match(orderMessage(cart,products),/57,97/);assert.match(orderMessage(cart,products),/confirmar a disponibilidade/);});
test('Todos os produtos têm imagens locais e preços consistentes',async()=>{assert.equal(products.length,41);for(const p of products){assert.ok(Number.isInteger(p.priceCents)&&p.priceCents>0);assert.ok(p.imageUrl.startsWith('assets/products/'));await access(new URL('../'+p.imageUrl,import.meta.url));}});

test('Pré-pedido segue o modelo com nome, bairro, frete e subtotal',()=>{const c=[{id:17,qty:1,variant:'P'},{id:19,qty:1,variant:'M'},{id:32,qty:1,variant:''}];const text=orderMessage(c,products,{name:' teste ',receipt:'entrega',neighborhood:' Centro '});assert.match(text,/PRÉ-PEDIDO:\nNome: teste\nBairro para entrega: Centro/);assert.match(text,/Subtotal estimado dos produtos: R\$\s94,97/);assert.match(text,/Forma de recebimento: entrega./);assert.match(text,/Taxa de entrega: consultar com os atendentes./);assert.match(text,/tamanho P, pacote com 38 fraldas/);});
test('Retirada não inclui bairro nem taxa de entrega',()=>{const text=orderMessage([{id:32,qty:2,variant:''}],products,{name:'Ana',receipt:'retirada',neighborhood:'Centro'});assert.match(text,/Nome: Ana/);assert.match(text,/Forma de recebimento: retirada na loja./);assert.doesNotMatch(text,/Bairro para entrega|Taxa de entrega|Centro/);assert.match(text,/21,98/);});
test('Preço específico do tamanho prevalece no carrinho e no pré-pedido',()=>{const p={...products.find(p=>p.id===7),variants:products.find(p=>p.id===7).variants.map(v=>v.size==='P'?{...v,priceCents:3199}:v)};const list=products.map(x=>x.id===7?p:x);const cart=[{id:7,variant:'P',qty:2}];assert.equal(cartTotal(cart,list),6398);assert.match(orderMessage(cart,list),/63,98/);});
