import test from 'node:test';
import assert from 'node:assert/strict';
import {dispatchNext,reconcilePublication,neuraiAction} from '../supabase/functions/admin-api/publication.js';
const env=k=>({GITHUB_DEPLOY_TOKEN:'server-only-test',GITHUB_REPOSITORY:'test/repo'})[k]||'';
test('audit identity comes from verified Auth user, never browser input',async()=>{
 let captured;
 await neuraiAction({body:{action:'price-batch',batchId:'b',version:1,rows:[],autoPublish:false,actor_email:'spoof@test.invalid',actor_id:'spoof'},user:{id:'verified-user',email:'verified@test.invalid'},env,db:{rpc:async(name,args)=>{captured={name,args};return {data:{id:'b',publication_id:null}};}}});
 assert.equal(captured.name,'neurai_save_batch');assert.equal(captured.args.actor_id,'verified-user');assert.equal(captured.args.actor_email,'verified@test.invalid');
});
function fakeDb(){const updates=[],calls=[];let job={id:'job-1'};return {updates,calls,setJob:v=>job=v,rpc:async(name,args)=>{calls.push({name,args});return {data:name==='catalog_dispatch_claim'?job:{id:'batch-1',publication_id:'job-1'},error:null};},from(){const query={update(v){updates.push(v);return query;},eq(){return query;},then(resolve){return Promise.resolve({data:[],error:null}).then(resolve);}};return query;}};}
test('dispatch uses one ID and server-side token; accepted does not mean published',async()=>{const db=fakeDb();let count=0;const result=await dispatchNext(db,env,async(url,init)=>{count++;assert.match(url,/workflows\/publish.yml\/dispatches$/);assert.equal(JSON.parse(init.body).inputs.publication_id,'job-1');assert.equal(init.headers.Authorization,'Bearer server-only-test');return {ok:true};});assert.equal(count,1);assert.match(result.notice,/Aguardando/);assert.equal(db.updates[0].dispatch_state,'accepted');assert.ok(!db.updates.some(u=>u.status==='published'));});
test('running publication prevents duplicate dispatch and missing credentials retain queued prices',async()=>{const db=fakeDb();db.setJob(null);let requests=0;await dispatchNext(db,env,async()=>{requests++;});assert.equal(requests,0);await dispatchNext(db,()=>'',async()=>{requests++;});assert.equal(requests,0);});
test('connection loss and server errors preserve uncertain delivery; definitive GitHub rejection fails only publication',async()=>{for(const failure of ['offline',500,403]){const db=fakeDb();await dispatchNext(db,env,async()=>{if(failure==='offline')throw Error('offline');return {ok:false,status:failure};});assert.equal(db.updates.at(-1).dispatch_state,failure===403?'rejected':'uncertain');assert.equal(db.updates.at(-1).status,failure===403?'failed':undefined);assert.ok(!db.calls.some(c=>c.name==='neurai_save_batch'));}});
test('Actions reconciliation checks deployment result instead of confusing callback failure with deployment failure',async()=>{for(const deployed of [true,false]){const db=fakeDb();await reconcilePublication(db,env,{id:'job-1',run_id:'123',status:'building'},async url=>({ok:true,json:async()=>url.endsWith('/123')?{status:'completed',conclusion:'failure'}:{jobs:[{steps:[{name:'Implantar no GitHub Pages',conclusion:deployed?'success':'failure'}]}]}}));assert.equal(db.calls[0].name,'catalog_publication_finish');assert.equal(db.calls[0].args.result_status,deployed?'published':'failed');}});
test('validation error never calls GitHub; saved batch is returned even if dispatch lookup fails',async()=>{let sent=0;const request={body:{action:'price-batch',batchId:'b',version:1,rows:[],autoPublish:true},user:{id:'actor'},env,fetcher:async()=>{sent++;}};await assert.rejects(()=>neuraiAction({...request,db:{rpc:async()=>({error:{message:'Preço inválido'}})}}),/Preço inválido/);assert.equal(sent,0);const result=await neuraiAction({...request,db:{rpc:async name=>name==='neurai_save_batch'?{data:{id:'b',publication_id:'p',changes:[]}}:{error:{message:'offline'}}}});assert.equal(result.batch.id,'b');assert.match(result.notice,/salvos/);assert.equal(sent,0);});
